version: "2"
services:

  ttf-taxnomomy-service:
    image: tti/ttf/taxonomyservice
    container_name: taxonomyservice
    volumes:
        - ../../artifacts:/app/artifacts
    environment:
        - gRpcHost=localhost
        - gRpcPort=8086
        - artifactPath=artifacts
    ports:
        - 8086:8086
    network_mode: "host"